services:
  discord_bot:
    image: netv_disc
    hostname: discord.netv.local
  

  whisper:
    image: netv_wisp
    hostname: whisper.netv.local
    ports:
      - 8080:8000
    volumes:
      - ./wisper/models:/app/models
      