services:
  discord_bot:
    image: netv_disc
    hostname: discord.netv.local
  

  whisper:
    image: netv_wisp
    hostname: whisper.netv.local
    volumes:
      - ./whisper/models:/root/.cache/whisper
      
  web:
    image: nginx
    volumes:
      - ./web/site/:/site
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
      
